### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference

### ISSUE THREAD

**Issue by Hosseinyzr** [mreram/ShowCaseView#21]
Hi,
I am using firebase test lab , and in almost tests I have this issue, in real and virtual devices:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
FATAL EXCEPTION: main
Process: ir.mytoon.app, PID: 7178
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
	at smartdevelop.ir.eram.showcaseviewlib.b.<init>(GuideView.java:99)
	at smartdevelop.ir.eram.showcaseviewlib.b.<init>(GuideView.java:36)
	at smartdevelop.ir.eram.showcaseviewlib.b$a.a(GuideView.java:587)
	at ir.mytoon.app.MyTest.MVP.Main.MainActivity.d(MainActivity.java:192)
	at ir.mytoon.app.MyTest.MVP.Main.MainActivity.c(MainActivity.java:174)
	at ir.mytoon.app.MyTest.MVP.Main.MainActivity.b(MainActivity.java:167)
	at ir.mytoon.app.MyTest.MVP.Main.MainActivity.a(MainActivity.java:382)
	at ir.mytoon.app.MyTest.MVP.Main.MainActivity.lambda$rPCInGqblCtQbczEtPHk2uci39Y(MainActivity.java)
	at ir.mytoon.app.MyTest.MVP.Main.-$$Lambda$MainActivity$rPCInGqblCtQbczEtPHk2uci39Y.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by Hosseinyzr** [comment]
Actually I found the reason, some times this issue occurs because the view is not created yet, so it is not a problem of this library , and i fixed my code...
thanks

**Comment by rajdeep-golan** [comment]
Check whether the SuperView is created successfully or not!
